#Flask settings
FLASK_APP = 'app.py'
FLASK_SERVER_NAME = 'airpuff'
FLASK_PORT= 5000
FLASK_DEBUG = True
FLASK_ENV = 'development'
#Flask-Restplus settings
REST_SWAGGER_UI_DOC_EXPANSION = 'list'
REST_VALIDATE = True
REST_MASK_SWAGGER =False
REST_ERROR_404_HELP = False
#JOBS
THREAD = 12
PROCESS = 1
MAX_INSTANCES = 5
INTERVAL_ESP_SECONDS = 5
INTERVAL_AILRY_SECONDS = 900
INTERVAL_ESP_REBOOT_MINUTES = 20
COALESCE = True
