import numpy as np
import skfuzzy as fuzz


def fmaximum(func1,func2):
    return np.fmax(func1,func2)

def getAggregate(counter,action,aggrs):

    if  counter  == 0:
        return fmaximum(action[counter-1],aggrs)
    else:
        if counter == len(action):
            aggr = fmaximum(action[counter-1],action[counter])
            return getAggregate(counter - 1, action, aggr)
        else:
            aggr = fmaximum(action[counter-1],aggrs)
            return getAggregate(counter -1,action,aggr)

def calculateIternalMandami(airlyCurrentMeassurment, espCurrentMeasurment, airlyForecastMeasurment):
    airly_current = np.arange(0, 1024, 1)
    airly_forecast = np.arange(0, 1024, 1)
    esp_current = np.arange(0, 1024, 1)
    fun = np.arange(0, 1024, 1)

    # Generate fuzzy membership functions
    airly_current_1 = fuzz.trimf(fun, [0, 0, 500])
    airly_current_2 = fuzz.trimf(fun, [200, 500, 700])
    airly_current_3 = fuzz.trimf(fun, [300, 600, 850])
    airly_current_4 = fuzz.trimf(fun, [500, 750 , 900])
    airly_current_5 = fuzz.trimf(fun, [750, 1024, 1024])

    esp_current_1 = fuzz.trimf(fun, [0, 0, 500])
    esp_current_2 = fuzz.trimf(fun, [200, 500, 700])
    esp_current_3 = fuzz.trimf(fun, [300, 600, 850])
    esp_current_4 = fuzz.trimf(fun, [500, 750 , 900])
    esp_current_5 = fuzz.trimf(fun, [750, 1024, 1024])

    airly_forecast_1 = fuzz.trimf(fun, [0, 0, 500])
    airly_forecast_2 = fuzz.trimf(fun, [200, 500, 700])
    airly_forecast_3 = fuzz.trimf(fun, [300, 600, 850])
    airly_forecast_4 = fuzz.trimf(fun, [500, 750 , 900])
    airly_forecast_5 = fuzz.trimf(fun, [750, 1024, 1024])

    fun_level_1 = fuzz.trimf(fun, [0, 0, 500])
    fun_level_2 = fuzz.trimf(fun, [200, 500, 700])
    fun_level_3 = fuzz.trimf(fun, [300, 600, 850])
    fun_level_4 = fuzz.trimf(fun, [500, 750 , 900])
    fun_level_5 = fuzz.trimf(fun, [750, 1024, 1024])

    # pobrane wartosci z skryptu connectDataBase
    # aktualne wartosci z ESP

    airly_current_very_lo = fuzz.interp_membership(airly_current, airly_current_1, airlyCurrentMeassurment)
    airly_current_lo = fuzz.interp_membership(airly_current, airly_current_2, airlyCurrentMeassurment)
    airly_current_md = fuzz.interp_membership(airly_current, airly_current_3, airlyCurrentMeassurment)
    airly_current_hi = fuzz.interp_membership(airly_current, airly_current_4, airlyCurrentMeassurment)
    airly_current_very_hi = fuzz.interp_membership(airly_current, airly_current_5, airlyCurrentMeassurment)

    esp_current_very_lo = fuzz.interp_membership(esp_current, esp_current_1, espCurrentMeasurment)
    esp_current_lo = fuzz.interp_membership(esp_current, esp_current_2, espCurrentMeasurment)
    esp_current_md = fuzz.interp_membership(esp_current, esp_current_3, espCurrentMeasurment)
    esp_current_hi = fuzz.interp_membership(esp_current, esp_current_4, espCurrentMeasurment)
    esp_current_very_hi = fuzz.interp_membership(esp_current, esp_current_5, espCurrentMeasurment)

    airly_forecast_very_lo = fuzz.interp_membership(airly_forecast, airly_forecast_1, airlyForecastMeasurment)
    airly_forecast_lo = fuzz.interp_membership(airly_forecast, airly_forecast_2, airlyForecastMeasurment)
    airly_forecast_md = fuzz.interp_membership(airly_forecast, airly_forecast_3, airlyForecastMeasurment)
    airly_forecast_hi = fuzz.interp_membership(airly_forecast, airly_forecast_4, airlyForecastMeasurment)
    airly_forecast_very_hi = fuzz.interp_membership(airly_forecast, airly_forecast_5, airlyForecastMeasurment)


    ###############################################################
    #IF
    activeRule = []
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_md, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_md, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_md, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_md, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_md, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_hi, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_lo, np.fmin(esp_current_very_hi, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_md, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_md, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_md, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_md, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_md, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_hi, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_lo, np.fmin(esp_current_very_hi, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_md, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_md, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_md, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_md, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_md, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_hi, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_md, np.fmin(esp_current_very_hi, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_md, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_md, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_md, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_md, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_md, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_hi, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_hi, np.fmin(esp_current_very_hi, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_lo, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_lo, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_lo, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_lo, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_lo, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_md, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_md, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_md, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_md, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_md, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_hi, airly_forecast_very_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_hi, airly_forecast_very_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_hi, airly_forecast_lo)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_hi, airly_forecast_md)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_hi, airly_forecast_hi)))
    activeRule.append(np.fmin(airly_current_very_hi, np.fmin(esp_current_very_hi, airly_forecast_very_hi)))

    action = []

    action.append(np.fmin(activeRule[0], fun_level_1))
    action.append(np.fmin(activeRule[1], fun_level_1))
    action.append(np.fmin(activeRule[2], fun_level_2))
    action.append(np.fmin(activeRule[3], fun_level_3))
    action.append(np.fmin(activeRule[4], fun_level_4))
    action.append(np.fmin(activeRule[5], fun_level_2))
    action.append(np.fmin(activeRule[6], fun_level_2))
    action.append(np.fmin(activeRule[7], fun_level_2))
    action.append(np.fmin(activeRule[8], fun_level_3))
    action.append(np.fmin(activeRule[9], fun_level_3))
    action.append(np.fmin(activeRule[10], fun_level_3))
    action.append(np.fmin(activeRule[11], fun_level_3))
    action.append(np.fmin(activeRule[12], fun_level_3))
    action.append(np.fmin(activeRule[13], fun_level_3))
    action.append(np.fmin(activeRule[14], fun_level_4))
    action.append(np.fmin(activeRule[15], fun_level_4))
    action.append(np.fmin(activeRule[16], fun_level_4))
    action.append(np.fmin(activeRule[17], fun_level_4))
    action.append(np.fmin(activeRule[18], fun_level_4))
    action.append(np.fmin(activeRule[19], fun_level_5))
    action.append(np.fmin(activeRule[20], fun_level_5))
    action.append(np.fmin(activeRule[21], fun_level_5))
    action.append(np.fmin(activeRule[22], fun_level_5))
    action.append(np.fmin(activeRule[23], fun_level_5))
    action.append(np.fmin(activeRule[24], fun_level_5))
    action.append(np.fmin(activeRule[25], fun_level_1))
    action.append(np.fmin(activeRule[26], fun_level_1))
    action.append(np.fmin(activeRule[27], fun_level_2))
    action.append(np.fmin(activeRule[28], fun_level_3))
    action.append(np.fmin(activeRule[29], fun_level_4))
    action.append(np.fmin(activeRule[30], fun_level_2))
    action.append(np.fmin(activeRule[31], fun_level_2))
    action.append(np.fmin(activeRule[32], fun_level_2))
    action.append(np.fmin(activeRule[33], fun_level_3))
    action.append(np.fmin(activeRule[34], fun_level_4))
    action.append(np.fmin(activeRule[35], fun_level_3))
    action.append(np.fmin(activeRule[36], fun_level_3))
    action.append(np.fmin(activeRule[37], fun_level_3))
    action.append(np.fmin(activeRule[38], fun_level_3))
    action.append(np.fmin(activeRule[39], fun_level_4))
    action.append(np.fmin(activeRule[40], fun_level_4))
    action.append(np.fmin(activeRule[41], fun_level_4))
    action.append(np.fmin(activeRule[42], fun_level_4))
    action.append(np.fmin(activeRule[43], fun_level_4))
    action.append(np.fmin(activeRule[44], fun_level_5))
    action.append(np.fmin(activeRule[45], fun_level_5))
    action.append(np.fmin(activeRule[46], fun_level_5))
    action.append(np.fmin(activeRule[47], fun_level_5))
    action.append(np.fmin(activeRule[48], fun_level_5))
    action.append(np.fmin(activeRule[49], fun_level_5))
    action.append(np.fmin(activeRule[50], fun_level_1))
    action.append(np.fmin(activeRule[51], fun_level_1))
    action.append(np.fmin(activeRule[52], fun_level_2))
    action.append(np.fmin(activeRule[53], fun_level_3))
    action.append(np.fmin(activeRule[54], fun_level_4))
    action.append(np.fmin(activeRule[55], fun_level_2))
    action.append(np.fmin(activeRule[56], fun_level_2))
    action.append(np.fmin(activeRule[57], fun_level_3))
    action.append(np.fmin(activeRule[58], fun_level_3))
    action.append(np.fmin(activeRule[59], fun_level_4))
    action.append(np.fmin(activeRule[60], fun_level_3))
    action.append(np.fmin(activeRule[61], fun_level_3))
    action.append(np.fmin(activeRule[62], fun_level_3))
    action.append(np.fmin(activeRule[63], fun_level_4))
    action.append(np.fmin(activeRule[64], fun_level_4))
    action.append(np.fmin(activeRule[65], fun_level_4))
    action.append(np.fmin(activeRule[66], fun_level_4))
    action.append(np.fmin(activeRule[67], fun_level_4))
    action.append(np.fmin(activeRule[68], fun_level_4))
    action.append(np.fmin(activeRule[69], fun_level_5))
    action.append(np.fmin(activeRule[70], fun_level_5))
    action.append(np.fmin(activeRule[71], fun_level_5))
    action.append(np.fmin(activeRule[72], fun_level_5))
    action.append(np.fmin(activeRule[73], fun_level_5))
    action.append(np.fmin(activeRule[74], fun_level_5))
    action.append(np.fmin(activeRule[75], fun_level_2))
    action.append(np.fmin(activeRule[76], fun_level_2))
    action.append(np.fmin(activeRule[77], fun_level_3))
    action.append(np.fmin(activeRule[78], fun_level_3))
    action.append(np.fmin(activeRule[79], fun_level_4))
    action.append(np.fmin(activeRule[80], fun_level_2))
    action.append(np.fmin(activeRule[81], fun_level_2))
    action.append(np.fmin(activeRule[82], fun_level_3))
    action.append(np.fmin(activeRule[83], fun_level_3))
    action.append(np.fmin(activeRule[84], fun_level_4))
    action.append(np.fmin(activeRule[85], fun_level_2))
    action.append(np.fmin(activeRule[86], fun_level_2))
    action.append(np.fmin(activeRule[87], fun_level_3))
    action.append(np.fmin(activeRule[88], fun_level_4))
    action.append(np.fmin(activeRule[89], fun_level_5))
    action.append(np.fmin(activeRule[90], fun_level_4))
    action.append(np.fmin(activeRule[91], fun_level_4))
    action.append(np.fmin(activeRule[92], fun_level_4))
    action.append(np.fmin(activeRule[93], fun_level_4))
    action.append(np.fmin(activeRule[94], fun_level_5))
    action.append(np.fmin(activeRule[95], fun_level_5))
    action.append(np.fmin(activeRule[96], fun_level_5))
    action.append(np.fmin(activeRule[97], fun_level_5))
    action.append(np.fmin(activeRule[98], fun_level_5))
    action.append(np.fmin(activeRule[99], fun_level_5))
    action.append(np.fmin(activeRule[100], fun_level_3))
    action.append(np.fmin(activeRule[101], fun_level_3))
    action.append(np.fmin(activeRule[102], fun_level_3))
    action.append(np.fmin(activeRule[103], fun_level_3))
    action.append(np.fmin(activeRule[104], fun_level_4))
    action.append(np.fmin(activeRule[105], fun_level_3))
    action.append(np.fmin(activeRule[106], fun_level_3))
    action.append(np.fmin(activeRule[107], fun_level_3))
    action.append(np.fmin(activeRule[108], fun_level_4))
    action.append(np.fmin(activeRule[109], fun_level_5))
    action.append(np.fmin(activeRule[110], fun_level_3))
    action.append(np.fmin(activeRule[111], fun_level_3))
    action.append(np.fmin(activeRule[112], fun_level_3))
    action.append(np.fmin(activeRule[113], fun_level_4))
    action.append(np.fmin(activeRule[114], fun_level_5))
    action.append(np.fmin(activeRule[115], fun_level_4))
    action.append(np.fmin(activeRule[116], fun_level_4))
    action.append(np.fmin(activeRule[117], fun_level_4))
    action.append(np.fmin(activeRule[118], fun_level_4))
    action.append(np.fmin(activeRule[119], fun_level_5))
    action.append(np.fmin(activeRule[120], fun_level_5))
    action.append(np.fmin(activeRule[121], fun_level_5))
    action.append(np.fmin(activeRule[122], fun_level_5))
    action.append(np.fmin(activeRule[123], fun_level_5))
    action.append(np.fmin(activeRule[124], fun_level_5))

    aggregate = getAggregate(len(action)-1,action,0)

    funResult = fuzz.defuzz(fun, aggregate, 'centroid')

    return funResult

